Models/Habit.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenORM.Models
{
    public class Habit
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        [ForeignKey("Creator")]
        public int CreatorId { get; set; }
        public User? Creator { get; set; }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

        public List<Like>? Likes { get; set; }
    }
}

Controllers/HabitController.cs
using ExamenORM.Data;
using ExamenORM.Filters;
using ExamenORM.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamenORM.Controllers
{
    [SessionCheck]
    public class HabitController : Controller
    {
        private LoginContext _context;

        public HabitController(LoginContext loginContext)
        {
            _context = loginContext;
        }

        [HttpGet("habits")]
        public IActionResult Index()
        {
            int? id = HttpContext.Session.GetInt32("UserId");
            HabitsList_indexView habitsList_IndexView = new HabitsList_indexView();
            List<Habit> youhabit = _context.Habits
                .Include(a => a.Category)
                .Include(a => a.Likes)
                .Include(a=>a.Creator)
                .Where(a => a.Creator.Id == id)
                .ToList();
            List<Habit> other = _context.Habits
                .Include(a => a.Category)
                .Include(a => a.Likes)
                .Include(a=>a.Creator)
                .ToList();

            habitsList_IndexView.YouHabit = youhabit;
            habitsList_IndexView.OtherHabit = other;
            return View(habitsList_IndexView);
        }

        [HttpGet("habits/new")]
        public IActionResult New()
        {
            HabitCategoryView habitCategoryView = new HabitCategoryView();
            habitCategoryView.Categories = _context.Categories.ToList();
            return View(habitCategoryView);
        }

        [HttpPost("habits/create")]
        public IActionResult Create([Bind(Prefix = "Habit")] Habit habit)
        {
            int? id = HttpContext.Session.GetInt32("UserId");
            if (id != null && id != habit.CreatorId)
            {
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                habit.CreatedAt = DateTime.Now;
                habit.UpdatedAt = DateTime.Now;
                _context.Habits.Add(habit);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                HabitCategoryView habitCategoryView = new HabitCategoryView();
                habitCategoryView.Categories = _context.Categories.ToList();
                habitCategoryView.Habit = habit;
                return View("New", habitCategoryView);
            }
        }

        [HttpGet("habits/{id}/edit")]
        public IActionResult Edit(int id)
        {
            Habit? habit = _context.Habits.FirstOrDefault(a => a.Id == id);
            if (habit == null)
            {
                return RedirectToAction("Index");
            }
            HabitCategoryView habitCategoryView = new HabitCategoryView();
            habitCategoryView.Categories = _context.Categories.ToList();
            habitCategoryView.Habit = habit;
            return View(habitCategoryView);
        }

        [HttpPost("habits/{id}/update")]
        public IActionResult Update(int id, [Bind(Prefix = "Habit")] Habit habit)
        {
            int? userid = HttpContext.Session.GetInt32("UserId");
            if (userid != null && userid != habit.CreatorId)
            {
                return RedirectToAction("Index");
            }
            Habit? updatehabit = _context.Habits
                .Include(a => a.Category)
                .FirstOrDefault(a=>a.CreatorId == userid && a.Id == id);
            if (updatehabit == null)
            {
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                updatehabit.CategoryId = habit.CategoryId;
                updatehabit.Title = habit.Title;
                updatehabit.Description = habit.Description;
                updatehabit.UpdatedAt = DateTime.Now;
                _context.Habits.Update(updatehabit);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                HabitCategoryView habitCategoryView = new HabitCategoryView();
                habitCategoryView.Categories = _context.Categories.ToList();
                habitCategoryView.Habit = habit;
                return View("Edit", habitCategoryView);
            }
        }

        [HttpPost("habits/{id}/destroy")]
        public IActionResult Delete(int id)
        {
            int? userid = HttpContext.Session.GetInt32("UserId");
            Habit? habit = _context.Habits.FirstOrDefault(a => a.Creator.Id == userid && a.Id == id);
            if (habit == null)
            {
                return RedirectToAction("Index");
            }
            List<Like> likes = _context.Likes.Where(a => a.Habit.Id == habit.Id).ToList();
            _context.Likes.RemoveRange(likes);
            _context.Habits.Remove(habit);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/LikeController.cs
using ExamenORM.Data;
using ExamenORM.Filters;
using ExamenORM.Migrations;
using ExamenORM.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamenORM.Controllers
{
    [SessionCheck]
    public class LikeController : Controller
    {
                private LoginContext _context;

        public LikeController(LoginContext loginContext)
        {
            _context = loginContext;
        }

        [HttpPost("likes/create/{habitid}")]
        public IActionResult Create(int habitid){
            int? id = HttpContext.Session.GetInt32("UserId");
            Habit? habit = _context.Habits.FirstOrDefault(a=>a.Id == habitid);
            User? user = _context.Users.FirstOrDefault(a=>a.Id == id);
            if(habit != null && user != null){
                Console.WriteLine("okkk..");
                Like like = new Like(){
                    CreatorId = user.Id,
                    Creator = user,
                    HabitId = habit.Id,
                    Habit = habit,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };
                _context.Likes.Add(like);
                _context.SaveChanges();
                return RedirectToAction("Index","Habit");
            }
                return RedirectToAction("Index","Habit");
        }
    }
}

Controllers/UserController.cs
using ExamenORM.Data;
using ExamenORM.Filters;
using ExamenORM.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamenORM.Controllers
{
    [SessionCheck]
    public class UserController : Controller
    {
        private LoginContext _context;

        public UserController(LoginContext loginContext)
        {
            _context = loginContext;
        }
        [HttpGet("users/{id}")]
        public IActionResult Show(int id)
        {
            UserHabits userHabits = new UserHabits();
            User? user = _context.Users.FirstOrDefault(a => a.Id == id);
            if (user == null)
            {
                return RedirectToAction("Index", "Habit");
            }

            userHabits.creatorName = user.Name;
            userHabits.Habits = _context.Habits
                .Include(a => a.Category)
                .Include(a => a.Likes).ThenInclude(a=>a.Creator)
                .Include(a => a.Creator)
                .Where(a => a.Creator.Id == id)
                .ToList();
            return View(userHabits);
        }
    }
}

Views/Habit/Edit.cshtml
@model HabitCategoryView
<h2>Edit Habit</h2>
@{
    int? id = Context.Session.GetInt32("UserId");
}
<form asp-action="Update" asp-controller="Habit" asp-route-id="@Model.Habit.Id">
    <input type="hidden" value="@id" asp-for="@Model.Habit.CreatorId" />
    <div class="blocks">
        <label asp-for="@Model.Habit.Title">Habit Title</label>
        <input asp-for="@Model.Habit.Title">
    </div>
    <div class="blocks">
        <span asp-validation-for="@Model.Habit.Title"></span>
    </div>
    <div class="blocks">
        <label asp-for="@Model.Habit.Description">Description</label>
        <textarea asp-for="@Model.Habit.Description"></textarea>
    </div>
    <div class="blocks">
        <span asp-validation-for="@Model.Habit.Description"></span>
    </div>

    <div class="blocks">
        <label asp-for="@Model.Habit.CategoryId">Category</label>
        <select asp-for="@Model.Habit.CategoryId">
            @foreach (Category category in @Model.Categories)
            {
                <option value="@category.Id">@category.Name</option>
            }
        </select>
    </div>
    <div class="blocks">
        <span asp-validation-for="@Model.Habit.CategoryId"></span>
    </div>

    <div class="blocks">
        <button type="submit" class="btn1 btnmmargin">Update habit</button>
    </div>
</form>

Views/Habit/Index.cshtml
@model HabitsList_indexView
@{
    int? userid = Context.Session.GetInt32("UserId");
}

<div class="habits">
    <div class="youhabit">
        <h2>You habits</h2>
        @foreach (Habit youhabit in @Model.YouHabit)
        {
            <div class="habit">
                <p class="habititle">@youhabit.Title
                    @if ((DateTime.Now - youhabit.UpdatedAt).TotalHours <= 24)
                    {
                        <span class="update">Updated!</span>
                    }
                </p>
                <p>@{
                        string result = "";
                        int i = youhabit.Likes.Count();
                        if (i == 0)
                        {
                            result = "No cheers yet!";
                        }
                        else if (i == 1)
                        {
                            result = "1 person is cheering you on!";
                        }
                        else
                        {
                            result = $"{youhabit.Likes.First().Creator.Name} and {i} others are cheering them on!";
                        }
                    }
                    @result</p>
                <p>@youhabit.Category.Name</p>
                <div class="button_link">
                    <form asp-action="Edit" asp-controller="Habit" asp-route-id="@youhabit.Id" method="get">
                        <button>Edit</button>
                    </form>

                    <form asp-action="Delete" asp-controller="Habit" asp-route-id="@youhabit.Id">
                        <button>Delete</button>
                    </form>
                </div>
            </div>
        }
    </div>

    <div>
        <h2>Other Habits</h2>
        @foreach (Habit otherhabit in @Model.OtherHabit)
        {
            <div class="otherhabits">
                <p class="othertitle"><a asp-controller="User" asp-action="Show" asp-route-id="@otherhabit.CreatorId">@otherhabit.Creator.Name</a>
                    is going to @otherhabit.Title
                    @if ((DateTime.Now - otherhabit.UpdatedAt).TotalHours <= 24)
                    {
                        <span class="update">Updated!</span>
                    }
                </p>
                <p>
                    @{
                        string result = "";
                        int i = otherhabit.Likes.Count();
                        if (i == 0)
                        {
                            result = "Give them their first cheer!";
                        }
                        else if (i == 1)
                        {
                            result = "1 person is cheering them on!";
                        }
                        else
                        {
                            result = $"{otherhabit.Likes.First().Creator.Name} and {i} others are cheering them on!";
                        }
                    }
                    @result
                </p>
                <div class="likebutton">
                    <p>@otherhabit.Category.Name</p>
                    @if (otherhabit.Likes.Any(a => a.CreatorId == userid))
                    {
                        <p>Thanks for the cheer!</p>
                    }
                    else
                    {
                        <form asp-action="Create" asp-controller="Like" asp-route-habitid="@otherhabit.Id">
                            <button type="submit" class="buttonpoint">Cheer On!</button>
                        </form>
                    }
                </div>
            </div>
        }
    </div>
</div>

Views/Habit/New.cshtml
@model HabitCategoryView
<h2>Start a Habit</h2>
@{
    int? id = Context.Session.GetInt32("UserId");
}
<form asp-action="Create" asp-controller="Habit">
    <input type="hidden" value="@id" asp-for="@Model.Habit.CreatorId" />
    <div class="blocks">
        <label asp-for="@Model.Habit.Title">Habit Title</label>
        <input asp-for="@Model.Habit.Title">
    </div>
    <div class="blocks">
        <span asp-validation-for="@Model.Habit.Title"></span>
    </div>
    <div class="blocks">
        <label asp-for="@Model.Habit.Description">Description</label>
        <textarea asp-for="@Model.Habit.Description"></textarea>
    </div>
    <div class="blocks">
        <span asp-validation-for="@Model.Habit.Description"></span>
    </div>

    <div class="blocks">
        <label asp-for="@Model.Habit.CategoryId">Category</label>
        <select asp-for="@Model.Habit.CategoryId">
            @foreach (Category category in @Model.Categories)
            {
                <option value="@category.Id">@category.Name</option>
            }
        </select>
    </div>
    <div class="blocks">
        <span asp-validation-for="@Model.Habit.CategoryId"></span>
    </div>

    <div class="blocks">
        <button type="submit"  class="btn1 btnmmargin">Get started!</button>
    </div>
</form>